### ISSUE TITLE
Subscription crashes on DateTime Result

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#990] opened 2024-11-11 05:21 UTC
Running the following subscription on the law enforcement example:
```
subscription {
  TrackingAlert {
    bolo_id
    last_updated
    latitude
    longitude
    registration_number
    registration_state
  }
}
```

crashes with

```
{
  "errors": [
    {
      "message": "Can't serialize value (/TrackingAlert/last_updated) : Invalid RFC3339 value : '2024-09-27 18:40:17.9Z'. because of : 'Text '2024-09-27 18:40:17.9Z' could not be parsed at index 10'",
      "path": [
        "TrackingAlert",
        "last_updated"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "TrackingAlert": null
  }
}
```

**Comment by henneberger** [comment] 2024-11-11 17:49
This is a duplicate of #806

**Closed by henneberger** 2024-11-11 17:49 UTC
