### ISSUE TITLE
Shadowjar step takes too much time in the build process

### ISSUE THREAD

**Issue by nandorsoma** [DataSQRL/sqrl#800] opened 2024-09-09 15:44 UTC
Currently, our development workflow involves a two-step process when changes are made to the Sqrl script. First, the script needs to be compiled with Sqrl, then we run `docker compose up --build`. The latter step is time-consuming as it involves a Gradle build that re-downloads all dependencies each time, which is unnecessary. A direct solution could be to mount the .m2/repositories folder from the host machine, but this is not feasible with Docker Compose.

A quick, albeit not ideal, solution would be to build an image with these dependencies by moving the shadowJar part earlier. However, we prefer not to maintain images if possible.

Therefore, we are seeking alternative options to reduce the build time. We're setting a time box of 4 hours for this investigation. If no better solution is found within this timeframe, we'll proceed with the aforementioned approach.

**Comment by henneberger** [comment] 2024-09-09 16:01
We started to move some of the dependencies to the Dockerfile. We can probably safely move the other dependencies over too.

**Comment by henneberger** [comment] 2024-10-16 18:50
Duplicate of #794

**Closed by henneberger** 2024-10-16 18:50 UTC
