### ISSUE TITLE
Enable Exporting and Importing of Logs

### ISSUE THREAD

**Issue by nandorsoma** [DataSQRL/sqrl#721] opened 2024-07-15 16:29 UTC
Make it possible to export to the log engine. This should be easy and should be done similarly to exporting to a logger.

The import part is tricky because the module loading happens before parsing the import statement.

This is how it should look like in sqrl:
```
EXPORT MyStateTable To log.MyStateTableAsStream:

IMPORT MyStateTableAsStream;
```

**Comment by henneberger** [comment] 2024-08-29 03:23
Duplicate of #731

**Closed by henneberger** 2024-08-29 03:23 UTC
