### ISSUE TITLE
Refactor Dependency Structure and Remove Redundancy

### ISSUE THREAD

**Issue by nandorsoma** [DataSQRL/sqrl#845] opened 2024-10-01 09:22 UTC
**Refactor Structure:** The current dependencies property is an array containing a single map, e.g.,
```
  "dependencies": [{
    "content" : {
      "name": "content-file",
      "version": "1",
      "variant": "dev"
    },
    "datasqrl.profile.default" : {
      "name": "datasqrl.profile.default",
      "version": "0.5.2",
      "variant": "dev"
    },
    "datasqrl.profile.redpanda" : {
      "name": "datasqrl.profile.redpanda",
      "version": "0.5.2",
      "variant": "dev"
    }
  }]
```
This should be either a map or an array for clarity and consistency.

**Remove Redundant Names:** Entries like "name": "content-file" are redundant if the key already identifies the dependency. Use either the key or the name, but not both.

**Comment by henneberger** [comment] 2024-10-16 18:03
Duplicate of #646

**Closed by henneberger** 2024-10-16 18:03 UTC
