### ISSUE TITLE
All rows have NULL values

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#328] opened 2023-08-24 18:20 UTC
Data discovery fails with an IllegalArgumentException if the input data has only NULL values for a particular field (i.e. all records have a null value in that field).

Instead, we should make the assumption that the field is a string (since we can always force cast to string) so Data discovery can complete successfully.

**Comment by henneberger** [comment] 2023-08-24 18:58
Duplicate of #151

**Closed** 2023-11-20 22:22 UTC
